blog: whats new may
Tresjs/tresjs.org pull request #12
Opened 2024-05-05 14:09 UTC by alvarosabu

2024-05-08 16:15 UTC, JaimeTorrealba commented
Ready when you are @alvarosabu

2024-05-19 21:50 UTC, garrlker commented on src/content/blog/whats-new-may-2024.md
> +Made by [emavitta-remago](https://github.com/Tresjs/cientos/commits?author=andretchen0)
Just noticed emavitta was linking to Andretchen, it should be this

```suggestion
Made by [emavitta-remago](https://github.com/Tresjs/cientos/commits?author=emavitta-remago)
```

2024-05-19 21:52 UTC, garrlker requested changes
Everything else looks good besides that contributor link

2024-05-20 09:22 UTC, JaimeTorrealba commented
Hi @garrlker thanks for point it, And sorry I left this one here open. This should be closed we decided to not do the blog post, instead a just tweeter/discord announce is enough for this (we will do one for the v4 of the core and another for v4 of cientos)

2024-05-20 09:22 UTC, closed without merging